# @name TODO 1
GET https://jsonplaceholder.typicode.com/todos/1

###

# @name TODO 2
GET https://jsonplaceholder.typicode.com/todos/2

###

# @name TODO 3
GET https://jsonplaceholder.typicode.com/todos/3

###

# @name TODO 4
GET https://jsonplaceholder.typicode.com/todos/4

###

# @name TODO 5
GET https://jsonplaceholder.typicode.com/todos/5

###

# @name TODO 6
GET https://jsonplaceholder.typicode.com/todos/6

###

# @name TODO 7
GET https://jsonplaceholder.typicode.com/todos/7

###

# @name TODO 8
GET https://jsonplaceholder.typicode.com/todos/8

###

# @name TODO 9
GET https://jsonplaceholder.typicode.com/todos/9

###

# @name TODO 10
GET https://jsonplaceholder.typicode.com/todos/10

###

# @name create httpbin user
# @write-body-to-temporary-file
POST https://httpbin.org/post HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "John",
  "age": 30,
  "address": "123 Main St, Springfield, IL 62701",
  "phone": "555-555-5555",
  "email": ""
}

### 
