quitOnTopLevelReturn: false

gui:
  sidePanelWidth: 0.3333 # number from 0 to 1

  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  border: 'rounded' # one of 'single' | 'double' | 'rounded' | 'hidden'

  # WARN: this theme dont work if you terminal have transparent. Work only in neovim without transparent background
  theme:
    # THEME: 'catppuccin'
    # activeBorderColor:
    #   - '#a6e3a1'
    #   - bold
    # inactiveBorderColor:
    #   - '#a6adc8'
    # searchingActiveBorderColor:
    #   - '#f9e2af'
    # optionsTextColor:
    #   - '#89b4fa'
    # selectedLineBgColor:
    #   - '#313244'
    # selectedRangeBgColor:
    #   - '#313244'
    # cherryPickedCommitBgColor:
    #   - '#45475a'
    # cherryPickedCommitFgColor:
    #   - '#a6e3a1'
    # unstagedChangesColor:
    #   - '#f38ba8'
    # defaultFgColor:
    #   - '#cdd6f4'

    # THEME: 'everforest dark'
    activeBorderColor:
      - '#a7c080'
      - bold
    inactiveBorderColor:
      - '#899c4040'
    searchingActiveBorderColor:
      - '#d3c6aa'
    optionsTextColor:
      - '#899c4040'
    selectedLineBgColor:
      - '#2d353b'
    selectedRangeBgColor:
      - '#3d484d90'
    cherryPickedCommitBgColor:
      - '#475258c0'
    cherryPickedCommitFgColor:
      - '#a7c080'
    unstagedChangesColor:
      - '#da6362'
    defaultFgColor:
      - '#d3c6aa'


# link: https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md#delta
git:
  paging:
    colorArg: always
    pager: delta --side-by-side --paging=never --line-numbers --true-color=always
    useConfig: false
    externalDiffCommand: "" 


customCommands:
  - key: '<C-n>'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it?'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'a feature branch'
            value: 'feature'
          - name: 'hotfix'
            description: 'a hotfix branch'
            value: 'hotfix'
          - name: 'release'
            description: 'a release branch'
            value: 'release'
      - type: 'input'
        title: 'What is the new branch name?'
        key: 'BranchName'
        initialValue: ''
    command: "git flow {{.Form.BranchType}} start {{.Form.BranchName}}"
    loadingText: 'Creating branch'
