gui:
  theme:
    activeBorderColor:
      - '#a6e3a1'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    selectedLineBgColor:
      - '#313244'
    optionsTextColor:
      - '#89b4fa'
stats:
  graphs:
    - caption: CPU (%)
      statPath: DerivedStats.CPUPercentage
      color: '#89b4fa'
    - caption: Memory (%)
      statPath: DerivedStats.MemoryPercentage
      color: '#a6e3a1'
