#!/bin/bash

find . -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) -print0 | xargs -0 mogrify -format webp
    find . -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) -delete
    notify-send -t 60000 "Mogrify completed!" "$(date)"; exit
