#!/bin/bash
#  .--. _                       .-.                                                             .-.                _             
# : .-':_;                      : :                                                             : :               :_;            
# : `; .-..-.,-.       .-.,-. .-' : .--.         .--.  .--. .--.  .--.  .--. ,-.,-.        .--. : `-.  .--.  .--. .-.,-.,-. .--. 
# : :  : :`.  .'       `.  .'' .; :' .; :       `._-.''  ..': ..'' '_.'' '_.': ,. :       `._-.': .. :' .; ; : ..': :: ,. :' .; :
# :_;  :_;:_,._; _____ :_,._;`.__.'`._. ; _____ `.__.'`.__.':_;  `.__.'`.__.':_;:_; _____ `.__.':_;:_;`.__,_;:_;  :_;:_;:_;`._. ;
#               :_____:             .-. ::_____:                                   :_____:                                  .-. :
#                                   `._.'                                                                                   `._.'

# Убиваем все конфликтующие порталы
pkill -f xdg-desktop-portal
pkill -f xdg-desktop-portal-.*

# Запускаем нужный портал (Hyprland или wlr)
if command -v /usr/lib/xdg-desktop-portal-hyprland &>/dev/null; then
    /usr/lib/xdg-desktop-portal-hyprland &
    export XDG_CURRENT_DESKTOP=Hyprland
else
    /usr/lib/xdg-desktop-portal-wlr &
    export XDG_CURRENT_DESKTOP=sway
fi

# Основной портал
/usr/lib/xdg-desktop-portal &
echo "Wayland порталы перезапущены."
