#!/bin/bash
#  .--. _                       .-.                                                             .-.                _             
# : .-':_;                      : :                                                             : :               :_;            
# : `; .-..-.,-.       .-.,-. .-' : .--.         .--.  .--. .--.  .--.  .--. ,-.,-.        .--. : `-.  .--.  .--. .-.,-.,-. .--. 
# : :  : :`.  .'       `.  .'' .; :' .; :       `._-.''  ..': ..'' '_.'' '_.': ,. :       `._-.': .. :' .; ; : ..': :: ,. :' .; :
# :_;  :_;:_,._; _____ :_,._;`.__.'`._. ; _____ `.__.'`.__.':_;  `.__.'`.__.':_;:_; _____ `.__.':_;:_;`.__,_;:_;  :_;:_;:_;`._. ;
#               :_____:             .-. ::_____:                                   :_____:                                  .-. :
#                                   `._.'                                                                                   `._.'

# sleep 1
# # kill all possible running xdg-desktop-portals
# killall -e xdg-desktop-portal-hyprland
# killall -e xdg-desktop-portal-gnome
# killall -e xdg-desktop-portal-kde
# killall -e xdg-desktop-portal-lxqt
# killall -e xdg-desktop-portal-wlr
# killall -e xdg-desktop-portal-gtk
# killall xdg-desktop-portal
# sleep 1
#
# # start xdg-desktop-portal-hyprland
# /usr/lib/xdg-desktop-portal-hyprland &
# sleep 2
#
# # start xdg-desktop-portal
# /usr/lib/xdg-desktop-portal &
# sleep 1
